apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: frontend
    newName: frontend
    newTag: k8s-dev
  - name: log-service
    newName: log-service
    newTag: k8s-dev