apiVersion: v1
kind: Secret
metadata:
  name: postgres-db
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: logs

---

apiVersion: v1
kind: Secret
metadata:
  name: log-service-db
type: Opaque
stringData:
  DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/logs