apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: frontend
    newName: ghcr.io/duongdinh7601/cloud-observability-platform/frontend
    newTag: replace-with-release-tag
  - name: log-service
    newName: ghcr.io/duongdinh7601/cloud-observability-platform/log-service
    newTag: replace-with-release-tag